### ISSUE TITLE
Support Steam China

### ISSUE THREAD

**Issue by cherinyy** [cantryDev/FixCSGOInventory#2]
Hello cantry,

Thank you for your work so that we can use Steam Community normally.

I wonder if you are willing to support the Steam China Community, although it is not online.

Currently I only know that its domain is my.steamchina.com

Thanks!

Best regards,
Gentry

**Comment by cantryDev** [comment]
Will look at it when Steam China is available

**Comment by cherinyy** [comment]
Steam China is available now.
My profile: https://my.steamchina.com/id/wordlesswind/inventory/#730

**Comment by cantryDev** [comment]
Inventory servers seem to be functional again. If the error comes back create a new issue. I will close this for now
